### ISSUE TITLE
Tags list don't update automatically after adding a tag

### ISSUE THREAD

**Issue by krnekhelesh** [turanmahmudov/PockIt2#22]
Steps to reproduce bug,
1. Open the Tags tab
2. Tag an article/image with a new tag (not present on the list)
3. Press save

Notice that the newly added tag is not present on the list. Even after syncing, closing and reopening the tag tab, the new tag doesn't appear.

The new tag only appears after restarting the app.

**Comment by turanmahmudov** [comment]
fixed

**Comment by krnekhelesh** [comment]
erm this bug isn't fixed. I just grabbed the code and tested it. I still don't see the new label I added without rebooting the app.

**Comment by turanmahmudov** [comment]
It works for me. I should test this on more devices.
Do you press enter key after type new tag?

**Comment by krnekhelesh** [comment]
I don't think this has got to do with what device I am running it on. I tested this on Nexus 4 and BQ. When I look at the commit https://github.com/turanmahmudov/PockIt2/commit/91be3f37bc36aca99b6d896b307514019f214b09 I don't see it updating the model as far as I can tell.

**Comment by turanmahmudov** [comment]
I marked "open" the bug again. 
`searchPage.home()` was giving an error, so removed it and it worked for me. Can you please record video the process or take screenshots with order?

**Comment by krnekhelesh** [comment]
I press "All UnTagged items" in the "Tags" tab which gave me a list of articles, I did not tag. So I tagged an article with the tag "lifehacks" and saved it. It appears in the article list with the tag I just created as shown in screenie 1.
Screenie 1: http://i.imgur.com/q42pE8i.png 

Now I open the "Tags" tab again, and notice how the tag "lifehacks" is missing. At this point, I press sync and try other stuff, but that tab is no where to be found.
Screenie 2: http://i.imgur.com/PkU8Uju.png

Now I reboot the app and then go to the "Tags" tab and now behold there is "lifehacks" tab.
Screenie 3: http://i.imgur.com/5QAU9wI.png

**Comment by turanmahmudov** [comment]
http://imgur.com/a/Om2LH
I opened the app: 1st image
clicked the tag action on an item: 2nd image
added new tag: 3rd image
clicked save and see new tag "git": 4th image
opened Tags tab and see new tag "git": 5th image
went to Untagged Items: 6th image
clicked the tag action on an item and added new tag: 7th image
clicked save and the item left the untagged items page: 8th image
went to Tags tab and see new tag "github": 9th image
